(defun html/grid ()
  "bootstrap 4 grid generate."
  (interactive)
  (let ((region-b (region-beginning))
	(region-e (region-end)))
    (setq block (buffer-substring region-b region-e))
    (setq block (split-string block "\n" t))
    (setq block (mapcar (lambda (x)
			  (split-string x "\s" t)) block))
    (setq block (mapcar (lambda (x)
			  (mapcar (lambda (y)
				    (concat "\n\t<div class=\"col-sm-" (if (string= y "0") "12" y) "\"></div>")) x)) block))
    (setq block (mapcar (lambda (x)
			  (concat "\n<div class=\"row\">" (apply 'concat x) "\n</div>")) block))
    (setq block (apply 'concat block))
    (delete-region region-b region-e)
    (insert block)))
